name: Production Deployment

on:
  push:
    branches:
      - main
    paths:
      - "databricks_bakehouse_analytics_project/**"

concurrency:
  group: production-deployment
  cancel-in-progress: false

jobs:
  deploy:
    name: Deploy bundle
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Databricks CLI
        uses: databricks/setup-cli@main

      - name: Deploy bundle
        run: databricks bundle deploy -t prod
        working-directory: databricks_bakehouse_analytics_project
        env:
          DATABRICKS_TOKEN: ${{ secrets.SP_TOKEN }}
          DATABRICKS_BUNDLE_ENV: prod
    
